#Highest number you can teleport to on the x axis
limit.x: 100
#Highest number you can teleport to on the y axis
limit.z: 100
#Lowest number you can teleport to on the x axis
limit.nx: -200
#Lowest number you can teleport to on the y axis
limit.nz: -200
Error:
  NumberConflict: The numbers set in the config do not work. setting to 1000...

  NNumberNotSet: The minimum numbers in the config are not set. Defaulting to -1000...

  NumberNotSet: The numbers in the config are not set. Defaulting to 1000...

  ConsoleSender: You must be a player to execute this command.

Teleported: You are now at #Coordinates go after this
